#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ca_64_r_8_ft
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate ldm
cd ~/fact/dp_lora
python main.py --base ./reproducibility_experiments/finetuning/celeba64-dp-eps10-rank8.yaml -t --gpus "0," --accelerator gpu -l logs/finetuning/celeba64