model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # Removed ckpt_path - trains from scratch
    beta_schedule: cosine
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 50
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 32
    channels: 4
    train_condition_only: true
    conditioning_key: crossattn
    monitor: val/loss
    cond_stage_trainable: false
    use_ema: false
    use_model_lora: true
    model_lora_r: 8
    model_lora_target: [to_q, to_v, to_k, to_out.0]
    use_cond_lora: false
    DPDM_k: 1
    dp_config:
      enabled: true
      epsilon: 1
      delta: 1.0e-05
      max_grad_norm: 0.0005
      poisson_sampling: true
      max_batch_size: 8
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 64           # Reduced from 256
        attention_resolutions:
        - 2
        num_res_blocks: 1            # Reduced from 2
        channel_mult:
        - 1
        - 2
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 16384
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 64                     # Reduced from 128
          ch_mult:
          - 1
          - 2
          num_res_blocks: 1          # Reduced from 2
          attn_resolutions: []       # Removed attention
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        embed_dim: 512
        key: class_label
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32                   # Increased from 16
    num_workers: 2                   # Reduced from 6
    wrap: false
    train:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: train
        target_type: class
        class_attrs:
        - Male
        size: 64                     # Reduced from 256
    validation:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: test
        target_type: class
        class_attrs:
        - Male
        size: 64
lightning:
  callbacks:
    rank_scheduler:
      target: main.RankSchedulerCallback
      params:
        scheduler_config:
          name: "linear"            
          initial_rank: 8
          final_rank: 4
          total_steps: 875          # (28000 / 32) * 1 epoch
        adapter_name: "default"
        log_interval: 5
  trainer:
    benchmark: false
    max_epochs: 1                   # Reduced from 10 - quick test
    accelerator: gpu