model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: /home/scur0003/fact/dp_lora/models/ldm/cin256/model.ckpt
    ignore_keys:
    - cond_stage_model
    beta_schedule: cosine
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 32
    channels: 4
    train_condition_only: true
    conditioning_key: crossattn
    monitor: val/loss
    cond_stage_trainable: true
    use_ema: false
    use_model_lora: true
    model_lora_r: 16
    model_lora_target: [to_q, to_v, to_k, to_out.0]
    use_cond_lora: false
    DPDM_k: 2
    dp_config:
      enabled: true
      epsilon: 10
      delta: 1.0e-05
      max_grad_norm: 0.0005
      poisson_sampling: true
      max_batch_size: 8
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 16384
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: [32]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        embed_dim: 512
        key: class_label
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2048
    num_workers: 6
    wrap: false
    train:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: train
        target_type: class
        class_attrs:
        - Male
        size: 256
    validation:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: test
        target_type: class
        class_attrs:
        - Male
        size: 256
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 3000
        max_images: 8
        increase_log_steps: false
    rank_scheduler:
      target: main.RankSchedulerCallback
      params:
        scheduler_config:
          name: "layer-wise"
          initial_rank: 16
          final_rank: 4
          schedule_type: "linear"
        adapter_name: "default"
  trainer:
    benchmark: true
    max_epochs: 10
    accelerator: gpu