model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    timesteps: 1000
    num_timesteps_cond: 1
    first_stage_key: image
    image_size: 32
    channels: 3
    monitor: val/loss
    use_ema: false
    log_every_t: 200
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_heads: 8
        use_scale_shift_norm: true
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: val/rec_loss
        ckpt_path: path/to/pretrained-autoencoder.ckpt
        embed_dim: 3
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0e-06
            disc_weight: 0.5
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 192
          ch_mult:
          - 1
          - 2
          num_res_blocks: 2
          attn_resolutions:
          - 16
          - 8
          dropout: 0.0
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 256
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        config:
          size: 64
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        config:
          size: 64

lightning:
  trainer:
    max_epochs: 40