#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ae_emnist_pt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate ldm
cd ~/fact/dp_lora
python main.py --base ./reproducibility_experiments/autoencoder/autoencoder_kl_emnist32_4x4x3.yaml -t --gpus "0," -l logs/autoencoder