#!/bin/bash

#SBATCH --job-name=count_params_mnist
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=0:10:00
#SBATCH --output=slurm_outputs/count_params_mnist_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate ldm
cd ~/fact/dp_lora

export PYTHONPATH="${PYTHONPATH}:${PWD}"

echo "MNIST Fine-tuned Model (eps=1)"
python ../scripts/count_model_params.py --ckpt logs/finetuning/mnist/2026-01-14T17-14-29_mnist32-class-dp-eps1/checkpoints/last.ckpt

echo ""
echo "MNIST Fine-tuned Model (eps=5)"
python ../scripts/count_model_params.py --ckpt logs/finetuning/mnist/2026-01-14T20-44-01_mnist32-class-dp-eps5/checkpoints/last.ckpt

echo ""
echo "MNIST Fine-tuned Model (eps=10)"
python ../scripts/count_model_params.py --ckpt logs/finetuning/mnist/2026-01-14T17-14-29_mnist32-class-dp-eps10/checkpoints/last.ckpt

echo ""
echo "EMNIST Pretrained Model"
python ../scripts/count_model_params.py --ckpt logs/latent-diffusion/2026-01-14T09-39-52_emnist32-conditional/checkpoints/last.ckpt
