#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=chqcosada
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=12:00:00
#SBATCH --output=slurm/cosada/slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate ldm
cd ~/fact/dp_lora
srun python main.py --base ./reproducibility_experiments/celebahq/celebahq-eps10-cosine-rank.yaml -t --gpus "0," --accelerator gpu -l logs/celebahq
