#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ldm_imnet32_uncond_pt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate ldm
cd ~/fact/dp_lora
srun python main.py --base ./reproducibility_experiments/latent-diffusion/imagenet32-unconditional.yaml -t --gpus "0," -l logs/latent-diffusion