model:
  base_learning_rate: 5.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: /root/autodl-tmp/2024-02-29T12-26-44_imagenet64-unconditional/checkpoints/epoch=000039.ckpt
    ignore_keys:
    - cond_stage_model
    linear_start: 0.0015
    linear_end: 0.0195
    timesteps: 1000
    num_timesteps_cond: 1
    first_stage_key: image
    image_size: 32
    channels: 3
    cond_stage_trainable: false
    train_attention_only: true
    use_ema: true
    monitor: val/loss
    log_every_t: 200
    
    use_model_lora: true
    model_lora_r: 64
    model_lora_target: [qkv, proj_out]
    use_cond_lora: false
    DPDM_k: 4
    
    dp_config:
      enabled: true
      epsilon: 10
      delta: 1.0e-06
      max_grad_norm: 0.0005
      poisson_sampling: true
      max_batch_size: 10
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_heads: 8
        use_scale_shift_norm: true
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: val/rec_loss
        embed_dim: 3
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0e-06
            disc_weight: 0.5
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 192
          ch_mult:
          - 1
          - 2
          num_res_blocks: 2
          attn_resolutions:
          - 16
          - 8
          dropout: 0.0
    cond_stage_config: __is_unconditional__
    ablation_blocks: -1
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8192
    num_workers: 6
    wrap: false
    train:
      target: ldm.data.celeba.CelebATrain
      params:
        config:
          size: 64
    validation:
      target: ldm.data.celeba.CelebAValidation
      params:
        config:
          size: 64
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: false
  trainer:
    benchmark: true
    max_epochs: 20
    accelerator: gpu